import Head from 'next/head';
import RegisterForm from './components/RegisterForm';

const Home: React.FC = () => {
  return (
    <div className="min-h-screen flex flex-col bg-gray-100">
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col md:flex-row w-full h-screen">
        <div className="w-full md:w-7/10 h-1/2 md:h-full bg-blue-500 flex items-center justify-center text-white text-center p-10">
          <div>
            <h1 className="text-4xl font-bold mb-4">Welcome to Our Landing Page</h1>
            <p className="text-lg">
              This is the main content area. It takes up 70% of the screen width on larger screens.
            </p>
          </div>
        </div>
        <div className="w-full md:w-3/10 h-1/2 md:h-full flex items-center justify-center p-10">
          <RegisterForm />
        </div>
      </main>
    </div>
  );
};

export default Home;
